### ISSUE TITLE
Map shows, but can't select a region.

### ISSUE THREAD

**Issue by zglezgle** [microsoft/landcover#14]
The first screen is good, where I chose the NAIP Maryland, new checkpoint, and start server. In the second screen, however, the mouse cursor doesn't turn into a square for me to select a region. Would you please help me? thanks!
![2020-07-27 08_36_22-Window](https://user-images.githubusercontent.com/5093203/88555380-fb126000-cfe4-11ea-8727-6bb541ba30fa.png)

**Comment by zglezgle** [comment]
Thank you! Shift-Click works.  Is it a new feature? In your live demo, I don't need to press Shift.  Thanks! http://landcoverdemo.eastus.cloudapp.azure.com:4040/

**Comment by zglezgle** [comment]
Another issue, see the above snapshot. There is no "Change Class Weights" controls in the right pane, but they exist in the live demo. Thanks!

**Comment by calebrob6** [comment]
Relatively new, that demo hasn't been updated in awhile :) I'll be updating the README page with instructions on using the tool shortly. (and I'm actively working on the items listed in TODO.md)

**Comment by calebrob6** [comment]
Yes, we have moved away from that feature. Now you can directly update the parameters of the last layer of the model by adding training samples and pressing the retrain button.

**Comment by zglezgle** [comment]
Thank you for your quick response! I really like the Change Class Weights" controls, which support some of my use cases. Would you please point me to the code how to get it back? I really appreciate your suggestions!

**Comment by calebrob6** [comment]
See the api branch of the project. Would love to hear about your use cases over email! caleb.robinson@microsoft.com
