### ISSUE TITLE
Problem with running inference on demo data 

### ISSUE THREAD

**Issue by laniaksalih** [microsoft/landcover#25]
First of all, thanks so much for sharing the source code for this awesome tool! Really excited to use it. 

I am running into an issue when I am trying to run inference on the demo data. The area that I shift click is not showing up on the right pane or showing the segmented version of the area either. It looks like this: 
<img width="1265" alt="Screen Shot 2021-06-09 at 11 57 26 AM" src="https://user-images.githubusercontent.com/60355490/121405217-c7a1a100-c92a-11eb-8287-53e2e27c03e3.png">

**Comment by calebrob6** [comment]
Do you see any errors in the terminal window that you're running the server on? If so, can you post a screenshot?

Also, can you look into the Chrome/Edge networking tab with developer tools open and try again, then post a screenshot of what is there?

**Comment by laniaksalih** [comment]
Thanks for your response. 

Here is what shows in the terminal window that I'm running the server on:
<img width="964" alt="Screen Shot 2021-06-09 at 2 46 49 PM" src="https://user-images.githubusercontent.com/60355490/121411358-882a8300-c931-11eb-8227-942ba0da88f0.png">

Here is the screenshot of the log:
<img width="1277" alt="Screen Shot 2021-06-09 at 2 45 44 PM" src="https://user-images.githubusercontent.com/60355490/121411203-6204e300-c931-11eb-8116-f338fbdd04f2.png">

**Comment by calebrob6** [comment]
Can you click on one of the failed requests, what is the error?

**Comment by calebrob6** [comment]
is this server public? is it possible for me to take a look?

**Comment by laniaksalih** [comment]
Yes it is. That would be great! http://52.138.96.130:8080/

**Comment by calebrob6** [comment]
You need to put the public IP in `endpoints.mine.js` (i.e. "http://52.138.96.130:8080/" instead of "http://10.1.0.4:8080/")

**Comment by laniaksalih** [comment]
Ok, I changed it. I'm running into a similar problem. 
<img width="1277" alt="Screen Shot 2021-06-09 at 4 16 53 PM" src="https://user-images.githubusercontent.com/60355490/121423305-1d337900-c93e-11eb-8edd-9ce77e01b116.png">

Here is the error message in the terminal
<img width="827" alt="Screen Shot 2021-06-09 at 4 15 55 PM" src="https://user-images.githubusercontent.com/60355490/121423398-3805ed80-c93e-11eb-90ef-9aa9ece6080e.png">

**Comment by calebrob6** [comment]
If you have time, do you mind emailing me at caleb.robinson@microsoft.com so we can setup a call to debug this?

**Comment by calebrob6** [comment]
The issue was that I had not committed a file in the latest update.
