### ISSUE TITLE
Missing segmentation_models_pytorch 

### ISSUE THREAD

**Issue by PatrickBue** [microsoft/landcover#26]
I am getting a file-not-found error when trying to run the line "import segmentation_models_pytorch as smp" in:
https://github.com/microsoft/landcover/blob/master/web_tool/ModelSessionPyTorchSegmentationModel.py#L27

Looks like segmentation_models_pytorch does not exist?

**Comment by calebrob6** [comment]
Hi Patrick, this is a python library - https://github.com/qubvel/segmentation_models.pytorch

**Comment by PatrickBue** [comment]
Thanks for the quick reply. Strange it didn't install the library while creating a new conda environment using "environment_precise.yml". Might have been a silent fail, seen that before with pip.
